### ISSUE TITLE
py.typed

### ISSUE THREAD

**Issue by ehossack** [escaped/django-admin-display#5]
Is there a reason why this project doesn't have a `py.typed` file in the module folder?
I'm new to mypy, but it's complaining that there's no typings unless I add that file in the `site-packages` directory.

I'd submit a PR, but it looks like the build is failing?

**Comment by b0g3r** [comment]
@escaped, could you please check this issue? Without it, mypy [thinks](https://www.python.org/dev/peps/pep-0561/#packaging-type-information) the package doesn't have typing support.

**Comment by escaped** [comment]
I just released `1.2.0`, which includes a `py.typed` file. :)
